### ISSUE TITLE
'from' namespacing not detected

### ISSUE THREAD

**Issue by CrackerJackMack** [ghewgill/pyqver#1]
Great script, wanted to say thanks!  I've only noticed one bug, which is 'from X import x,y'  syntax isn't properly detected due to name spacing being clobbered by the import line.

I looked at the code but wasn't sure how to handle that in the current structure.  Just thought I'd put this here in case someone else notices this as well.

Works really well otherwise.  :D

**Comment by ghewgill** [comment]
Fixed by https://github.com/ghewgill/pyqver/commit/c9fb943aca8f241490dadb92b5a929c7738c2e9b
